[project]
name = "templateer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "confidantic",
]

[tool.uv.sources]
confidantic = { git = "https://github.com/Bullish-Design/confidantic.git" }
