"""Template scaffold workflow shared by scripts/CLI wrappers."""

from __future__ import annotations

import json
import re
from pathlib import Path

from templateer.registry import build_registry_file
from templateer.services.runtime import resolve_project_root


def validate_template_id(template_id: str) -> str:
    candidate = template_id.strip()
    if not candidate:
        raise ValueError("template-id cannot be empty")
    if not re.fullmatch(r"[a-zA-Z0-9][a-zA-Z0-9_-]*", candidate):
        raise ValueError("template-id must match [a-zA-Z0-9][a-zA-Z0-9_-]*")
    return candidate


def parse_tags(raw_tags: str) -> list[str]:
    tags: list[str] = []
    for raw in raw_tags.split(","):
        tag = raw.strip()
        if tag:
            tags.append(tag)
    return tags


def write_if_missing(path: Path, content: str) -> None:
    if path.exists():
        return
    path.write_text(content, encoding="utf-8")


def scaffold_template(
    *,
    project_root: str | Path,
    template_id: str,
    model_import_path: str,
    description: str = "",
    tags: str = "",
) -> tuple[Path, Path]:
    """Create a new template scaffold and rebuild templates/registry.json."""

    canonical_template_id = validate_template_id(template_id)
    root = resolve_project_root(project_root)
    new_template_dir = root / "templates" / canonical_template_id

    if new_template_dir.exists() and any(new_template_dir.iterdir()):
        raise ValueError(f"Template already exists and is not empty: {new_template_dir}")

    (new_template_dir / "examples").mkdir(parents=True, exist_ok=True)
    (new_template_dir / "gen").mkdir(parents=True, exist_ok=True)

    manifest_payload = {
        "model_import_path": model_import_path,
        "description": description or f"Template for {canonical_template_id}",
        "tags": parse_tags(tags),
    }

    write_if_missing(new_template_dir / "manifest.json", json.dumps(manifest_payload, indent=2) + "\n")
    write_if_missing(
        new_template_dir / "README.md",
        f"# {canonical_template_id}\n\n"
        f"Describe the purpose, expected input model, and output contract for `{canonical_template_id}`.\n",
    )
    write_if_missing(
        new_template_dir / "template.mako",
        """## Generated by templateer scaffold\n${content if 'content' in locals() else ''}\n""",
    )
    write_if_missing(new_template_dir / "examples" / "sample_inputs.jsonl", "{}\n")
    write_if_missing(new_template_dir / "gen" / ".gitkeep", "")

    registry_path = build_registry_file(root)
    return new_template_dir, registry_path
