#!/usr/bin/env python3
"""Scaffold a new template folder and refresh templates/registry.json."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = REPO_ROOT / "src"
if SRC_DIR.exists() and str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from templateer.registry import build_registry_file


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Create a new template scaffold")
    parser.add_argument("--project-root", type=Path, default=Path("."), help="Project root containing templates/")
    parser.add_argument("--template-id", required=True, help="Template id and folder name under templates/")
    parser.add_argument("--model-import-path", required=True, help="Pydantic model import path, e.g. pkg.module:ClassName")
    parser.add_argument("--description", default="", help="Template description for manifest.json")
    parser.add_argument("--tags", default="", help="Comma-separated tag list")
    return parser


def validate_template_id(template_id: str) -> str:
    candidate = template_id.strip()
    if not candidate:
        raise ValueError("template-id cannot be empty")
    if not re.fullmatch(r"[a-zA-Z0-9][a-zA-Z0-9_-]*", candidate):
        raise ValueError("template-id must match [a-zA-Z0-9][a-zA-Z0-9_-]*")
    return candidate


def parse_tags(raw_tags: str) -> list[str]:
    tags: list[str] = []
    for raw in raw_tags.split(","):
        tag = raw.strip()
        if tag:
            tags.append(tag)
    return tags


def write_if_missing(path: Path, content: str) -> None:
    if path.exists():
        return
    path.write_text(content, encoding="utf-8")


def app(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        template_id = validate_template_id(args.template_id)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    project_root = Path(args.project_root)
    template_dir = project_root / "templates" / template_id

    if template_dir.exists() and any(template_dir.iterdir()):
        print(f"Template already exists and is not empty: {template_dir}", file=sys.stderr)
        return 1

    (template_dir / "examples").mkdir(parents=True, exist_ok=True)
    (template_dir / "gen").mkdir(parents=True, exist_ok=True)

    manifest_payload = {
        "model_import_path": args.model_import_path,
        "description": args.description or f"Template for {template_id}",
        "tags": parse_tags(args.tags),
    }

    write_if_missing(template_dir / "manifest.json", json.dumps(manifest_payload, indent=2) + "\n")
    write_if_missing(
        template_dir / "README.md",
        f"# {template_id}\n\nDescribe the purpose, expected input model, and output contract for `{template_id}`.\n",
    )
    write_if_missing(
        template_dir / "template.mako",
        """## Generated by templateer scaffold\n${content if 'content' in locals() else ''}\n""",
    )
    write_if_missing(template_dir / "examples" / "sample_inputs.jsonl", "{}\n")
    write_if_missing(template_dir / "gen" / ".gitkeep", "")

    try:
        registry_path = build_registry_file(project_root)
    except Exception as exc:
        print(f"Template scaffolded, but failed to build registry: {exc}", file=sys.stderr)
        return 1

    print(f"Created template scaffold at: {template_dir}")
    print(f"Updated registry: {registry_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(app())
